### ISSUE TITLE
rlx server crashes in case of insufficient memory

### ISSUE THREAD

**Issue by StanislavVolodarskiy** [deeplearninc/relaax#20]
The callstack is
Traceback (most recent call last):
  File "/usr/local/bin/relaax-rlx-server", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/relaax/bin/relaax-rlx-server", line 3, in <module>
    main()
  File "/relaax/relaax/server/rlx_server/main.py", line 56, in main
    timeout=args.timeout
  File "/relaax/relaax/server/rlx_server/server.py", line 22, in run
    timeout=timeout
  File "/relaax/relaax/server/rlx_server/server.py", line 50, in _run_agents
    required = _memory_per_child()
  File "/relaax/relaax/server/rlx_server/server.py", line 102, in _memory_per_child
    mem += _process_tree_memory(child)
  File "/relaax/relaax/server/rlx_server/server.py", line 109, in _process_tree_memory
    mem = process.memory_percent()
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1126, in memory_percent
    metrics = fun()
  File "/usr/local/lib/python2.7/dist-packages/psutil/_common.py", line 293, in wrapper
    return fun(self)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1086, in memory_info
    return self._proc.memory_info()
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1090, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=13606)

**Comment by StanislavVolodarskiy** [comment]
Fixed.
https://github.com/deeplearninc/relaax/commit/7b421fa86613baffef3f7fecc52cac6ecc567eb8
https://github.com/deeplearninc/relaax/commit/d2c117be751eb87c4ebf3c32d9fb7df7855fb2b2
